/** @jsxImportSource @emotion/react */
import api from "../libs/api";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import ProfileSection from "../components/Profilesection/ProfileSection";
import PersonSection from "../components/Personsection/PersonSection";
import PhotosSection from "../components/PhotosSection/PhotosSection";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Grid } from "@mui/material";
import { Typography } from "@mui/material";

import { useEffect } from "react";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      light: "#fff",
      dark: "#f5f5f5",
    },
  },
});

export default function Home() {
  // useEffect(async () => {
  //   await api();
  // }, []);

  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <header>
          <Navbar />
        </header>
        {/*Main body start  */}
        <main>
          <Box className="main-page">
            <Grid container spacing={1} className="top-page-grid">
              <Grid
                item
                xs={12}
                md={6}
                sm={6}
                lg={3}
                className="profile-section"
              >
                <ProfileSection />
              </Grid>
              <Grid
                item
                xs={12}
                md={6}
                sm={6}
                lg={3}
                className="profile-section"
              >
                <PersonSection />
              </Grid>
              <Grid item xs={12} md={12} sm={12} lg={5.8}>
                <PhotosSection />
              </Grid>
            </Grid>
          </Box>
        </main>

        {/* Main body end--------------- */}
      </div>
    </ThemeProvider>
  );
}
