/** @jsxImportSource @emotion/react */
import api from "../libs/api";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import ProfileSection from "../components/ProfileSection/ProfileSection";
import PersonSection from "../components/PersonSection/PersonSection";
import PhotosSection from "../components/PhotosSection/PhotosSection";
import SearchSection from '../components/SearchSection/SearchSection'

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Grid } from "@mui/material";
import { Typography } from "@mui/material";

import { useEffect,useState } from "react";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      light: "#fff",
      dark: "#f5f5f5",
    },
  },
});

export default function Home() {
  // useEffect(async () => {
  //   await api();
  // }, []);
  const [isLoading,setLoading]=useState(false)
  const [isSearching,setSearching]=useState(true)

  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <header>
          <Navbar />
        </header>
        {/*Main body start  */}
        <main>
          <Box className="main-page">
            <Grid container spacing={0} className="top-page-grid">
              <Grid
                item
                xs={12}
                md={6}
                sm={6}
                lg={3}
                className="profile-section"
              >
                <ProfileSection />
              </Grid>
              
                {!isSearching && !isLoading && <Grid
                item
                xs={12}
                md={6}
                sm={6}
                lg={3}
                className="person-section"
              ><PersonSection />
              </Grid>}
                {isSearching && !isLoading &&<Grid
                item
                xs={12}
                md={6}
                sm={6}
                lg={3}
                className="person-section"
              ><SearchSection />
              </Grid>}
              
              <Grid item xs={12} md={12} sm={12} lg={6}>
                <PhotosSection />
              </Grid>
              </Grid>
           
          </Box>
        </main>

        {/* Main body end--------------- */}
      </div>
    </ThemeProvider>
  );
}
