/** @jsxImportSource @emotion/react */
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import ProfileSection from "../components/Profilesection/ProfileSection";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Grid } from "@mui/material";
import { Typography } from "@mui/material";
import Paper from "@mui/material/Paper";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      light: "#fff",
      dark: "#f5f5f5",
    },
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <header>
          <Navbar />
        </header>
        {/*Main body start  */}
        <main>
          <Box className="main-page">
            <Grid container spacing={1} className="top-page-grid">
              <Grid item xs={3} className="profile-section">
                <ProfileSection />
              </Grid>
            </Grid>
          </Box>
        </main>

        {/* Main body end--------------- */}
      </div>
    </ThemeProvider>
  );
}
